In [5]:
import tiktoken
import torch

from src.configs import GPT_CONFIG_124M
from src.model.llm.gpt2 import GPT2Model

torch.manual_seed(123)

In [4]:
model = GPT2Model(GPT_CONFIG_124M)

In [6]:
tokenizer = tiktoken.get_encoding('gpt2')

batch = []

text1 = 'Every effort moves you'
text2 = 'Every day holds a'

batch.append(torch.tensor(tokenizer.encode(text1)))
batch.append(torch.tensor(tokenizer.encode(text2)))
batch = torch.stack(batch, dim=0)
print(batch)

tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])


In [8]:
out = model(batch)
print('Input batch:\n', batch)
print('Output shape:\n', out.shape)
print('Output batch:\n', out)

Input batch:
 tensor([[6109, 3626, 6100,  345],
        [6109, 1110, 6622,  257]])
Output shape:
 torch.Size([2, 4, 50257])
Output batch:
 tensor([[[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]],

        [[nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan],
         [nan, nan, nan,  ..., nan, nan, nan]]], grad_fn=<UnsafeViewBackward0>)
